export const PRODUCT_RULES = {
  MAX_NAME_LENGTH: 10,
  MIN_NAME_LENGTH: 1,
  MAX_PRICE: 10000,
  MIN_PRICE: 100,
  MIN_QUANTITY: 1,
  MAX_QUANTITY: 20,
  PRICE_MOD_UNIT: 10,
};

export const ERROR_MESSAGE = {
  EMPTY_PRODUCT_NAME: '상품명을 입력해주세요!',
  OUT_OF_RANGE_PRODUCT_NAME: `상품명은 ${PRODUCT_RULES.MIN_NAME_LENGTH}이상 ${PRODUCT_RULES.MAX_NAME_LENGTH}이하로 입력해주세요!`,
  OUT_OF_RANGE_PRODUCT_PRICE: `상품 가격은 ${PRODUCT_RULES.MIN_PRICE}이상 ${PRODUCT_RULES.MAX_PRICE}이하로 입력해주세요!`,
  INDIVISIBLE_PRICE_MOD_UNIT: `상품 가격은 ${PRODUCT_RULES.PRICE_MOD_UNIT}의 배수로 입력해주세요!`,
  OUT_OF_RANGE_PRODUCT_QUANTITY: `상품 수량은 ${PRODUCT_RULES.MIN_QUANTITY}이상 ${PRODUCT_RULES.MAX_QUANTITY}이하로 입력해주세요!`,
  OVERLAP_PRODUCT: '이미 존재하는 상품입니다!',
};
