export const ID = {
  CONTENT: 'content',
  ITEM_MANAGE_TAB_BUTTON: 'item-manage-tab-button',
  COIN_RECHARGE_TAB_BUTTON: 'coin-recharge-tab-button',
  ITEM_PURCHASE_TAB_BUTTON: 'item-purchase-tab-button',
  ITEM_INFO_FORM: 'item-info-form',
  CASH_CHARGE_FORM: 'cash-charge-form',
  CHARGED_AMOUNT: 'charged-amount',
  LOGIN_FORM: 'login-form',
  USER_INFO_FORM: 'user-info-form',
  EDIT_BUTTON: 'edit-button',
  LOGOUT_BUTTON: 'logout-button',
};

export const CLASS = {
  NAV_TAB_BUTTON: 'nav-tab-button',
  SELECTED: 'selected',
  ITEM_INFO_INPUT: 'item-info-input',
  ITEM_STATUS_TABLE: 'item-status-table',
  ITEM_INFO_INPUT_CELL: 'item-info-input-cell',
  ITEM_BUTTON_CELL: 'item-button-cell',
  HIDE: 'hide',
  EDIT_ITEM_BUTTON: 'edit-item-button',
  DELETE_ITEM_BUTTON: 'delete-item-button',
  CONFIRM_ITEM_BUTTON: 'confirm-item-button',
  CASH_CHARGE_INPUT: 'cash-charge-input',
  COIN_COUNT: 'coin-count',
  AUTHENTICATION_INPUT: 'authentication-input',
  THUMBNAIL_BUTTON: 'thumbnail-button',
  SIDE_BUTTON_WRAPPER: 'side-button-wrapper',
  PURCHASE_ITEM_BUTTON: 'purchase-item-button',
  RETURN_BUTTON: 'return-button',
};
