export const VENDING_MACHINE = {
  MIN_PRODUCT_NAME: 1,
  MAX_PRODUCT_NAME: 10,

  MIN_PRODUCT_PRICE: 100,
  MAX_PRODUCT_PRICE: 10000,

  MIN_PRODUCT_QUANTITY: 1,
  MAX_PRODUCT_QUANTITY: 20,

  MAX_HOLDING_AMOUNT: 100000,
  MAX_CHARGED_AMOUNT: 10000,

  MONEY_UNIT: 10,
};

export const ERROR_MESSAGE = {
  PRODUCT_NAME_REQUIRED: '상품명을 입력해주세요.',
  PRODUCT_NAME_LENGTH: `상품명은 ${VENDING_MACHINE.MIN_PRODUCT_NAME}자에서 ${VENDING_MACHINE.MAX_PRODUCT_NAME}자까지 입력할 수 있습니다.`,

  PRODUCT_PRICE_ONLY_NUMBER: '상품 가격은 숫자만 입력할 수 있습니다.',
  PRODUCT_PRICE_WRONG_RANGE: `상품 가격은 ${VENDING_MACHINE.MIN_PRODUCT_PRICE}원에서 ${VENDING_MACHINE.MAX_PRODUCT_PRICE}원까지 입력할 수 있습니다.`,
  PRODUCT_PRICE_WRONG_UNIT: `상품 가격은 ${VENDING_MACHINE.MONEY_UNIT}원 단위로 입력할 수 있습니다.`,

  PRODUCT_QUANTITY_ONLY_NUMBER: '상품 수량은 숫자만 입력할 수 있습니다.',
  PRODUCT_QUANTITY_WRONG_RANGE: `상품 수량은 ${VENDING_MACHINE.MIN_PRODUCT_QUANTITY}개에서 최대 ${VENDING_MACHINE.MAX_PRODUCT_QUANTITY}개까지만 입력할 수 있습니다.`,

  HOLDING_AMOUNT_ONLY_NUMBER: '추가할 보유 금액은 숫자만 입력할 수 있습니다.',
  HOLDING_AMOUNT_WRONG_UNIT: `추가할 자판기 보유 금액은 ${VENDING_MACHINE.MONEY_UNIT}원 단위로 입력할 수 있습니다.`,
  HOLDING_AMOUNT_WRONG_LIMIT: `자판기 보유 금액은 ${VENDING_MACHINE.MAX_HOLDING_AMOUNT}원까지 충전할 수 있습니다.`,

  USER_EMAIL_TYPE_WRONG: '이메일 주소를 정확히 입력해주세요.',
  USER_NAME_WRONG_RANGE: '이름은 1자에서 6자 이내로 입력하여야 합니다.',
  USER_PASSWORD_TYPE_WRONG: '비밀번호는 숫자와 영문을 포함하여 6자리 이상 입력하여야 합니다.',
  USER_PASSWORD_CONFIRM_DIFF: '비밀번호를 다시 확인해주세요.',
};

export const COIN_TYPE = [500, 100, 50, 10].sort((a, b) => b - a);

export const DEFAULT_PAGE = 'purchase';

export const USER_SESSION_SETTING = {
  EXPIRE_TIME: 1 * 60 * 60,
  TOKEN_COOKIE_NAME: 'SESSION_TOKEN',
  USER_INFO_STORAGE_NAME: 'SESSION_USER_INFO',
};
