export const SELECTOR = {
  ID: {
    APP: '#app',
    CONTENT: '#content',
    CHARGE_MONEY_FORM: '#charge-money-form',
    CURRENT_CHARGE_MONEY: '#current-charge-money',
    ADD_ITEM_NAME: '#add-item-name',
    ADD_ITEM_PRICE: '#add-item-price',
    ADD_ITEM_QUANTITY: '#add-item-quantity',
    ADD_ITEM_FORM: '#add-item-form',
    INPUT_MONEY_SUBMIT: '#input-money-submit',
    PURCHASE_ITEM_TABLE: '#purchase-item-table',
    CHANGE_COINS_TABLE: '#change-coins-table',
    CURRENT_INPUT_MONEY: '#current-input-money',
    SIGN_MAIN: '#sign-main',
    EDIT_SUBMIT: '#edit-submit',
    EDIT_EMAIL_INPUT: '#edit-email-input',
    NAME_INPUT: '#name-input',
    EMAIL_INPUT: '#email-input',
    PASSWORD_INPUT: '#password-input',
    PASSWORD_CONFIRM_INPUT: '#password-confirm-input',
    SIGNIN_SUBMIT: '#signin-submit',
    OFFER_SIGNUP_BUTTON: '#offer-signup-button',
    SIGNUP_SUBMIT: '#signup-submit',
    MENU_EDIT_PROFILE: '#menu-edit-profile',
    MENU_SIGN_OUT: '#menu-sign-out',
    USER_MENU: '#user-menu',
    SIGN_BUTTON: '#sign-button',
    ITEM_MANAGE_TAB: '#item-manage-tab',
    MONEY_CHARGE_TAB: '#money-charge-tab',
    PURCHASE_ITEM_TAB: '#item-purchase-tab',
    SNACKBAR: '#snackbar',
  },

  CLASS: {
    CHARGE_MONEY_INPUT: '.charge-money-input',
    COIN_TABLE: '.coin-table',
    NAV_CONTAINER: '.nav-container',
    NAV_BUTTON: '.nav-button',
    ITEM_TABLE_BUTTON_CONTAINER: '.item-table-button-container',
    TABLE_CONTAINER: '.table-container',
    ITEM_TABLE: '.item-table',
    ITEM_TABLE_BODY: '.item-table-body',
    ITEM_TABLE_CONFIRM_BUTTON: '.item-table-confirm-button',
    ITEM_TABLE_DELETE_BUTTON: '.item-table-delete-button',
    ITEM_TABLE_CHANGE_BUTTON: '.item-table-change-button',
    RETURN_CHANGE_BUTTON: '.return-change-button',
  },
  ID_STRING: {
    ITEM_MANGE_TAB: 'item-manage-tab',
    MONEY_CHARGE_TAB: 'money-charge-tab',
    ITEM_PURCHASE_TAB: 'item-purchase-tab',
  },
  CLASS_STRING: {
    NAV_BUTTON_CLICKED: 'nav-button-clicked',
    TABLE_ITEM_NAME: 'table-item-name',
    TABLE_ITEM_PRICE: 'table-item-price',
    TABLE_ITEM_QUANTITY: 'table-item-quantity',
    TABLE_ITEM_INPUT_NAME: 'table-item-input-name',
    TABLE_ITEM_INPUT_PRICE: 'table-item-input-price',
    TABLE_ITEM_INPUT_QUANTITY: 'table-item-input-quantity',
    ITEM_TABLE_CHANGE_BUTTON: 'item-table-change-button',
    ITEM_TABLE_DELETE_BUTTON: 'item-table-delete-button',
    ITEM_TABLE_CONFIRM_BUTTON: 'item-table-confirm-button',
    ITEM_TABLE_PURCHASE_BUTTON: 'item-table-purchase-button',
    SIGN_IN: 'sign-in',
    THUMBNAIL: 'thumbnail',
    THUMBNAIL_ACTIVE: 'thumbnail-active',
    DISPLAY_NONE: 'display-none',
    SHOW: 'show',
  },
};
