const PRODUCT = {
  MIN_PRICE: 100,
  MAX_PRICE: 10000,
  UNIT: 10,
  MAX_LENGTH: 10,
  MIN_QUANTITY: 1,
  MAX_QUANTITY: 20,
};

const CHARGE = {
  MIN_PRICE: 10,
  MAX_PRICE: 100000,
  UNIT: 10,
};

const INFOMATION_MESSAGES = {
  ASK_DELETE: "정말 삭제하시겠습니까?",
};

export { PRODUCT, CHARGE, INFOMATION_MESSAGES };
